name: Build Windows EXE with Nuitka

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Memungkinkan eksekusi manual (sekali tembak)

jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: ./bintang_ocr

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8' # Sesuai kompatibilitas Windows 7
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compile with Nuitka
      run: |
        # Otomatis setujui unduhan Dependency Walker tanpa interaksi manual
        echo Y | python -m nuitka --onefile --windows-disable-console --output-dir=build main.py
      shell: pwsh

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BINTANG-OCR-PRO
        path: bintang_ocr/build/main.exe
        retention-days: 7
